### ISSUE TITLE
Purescript 0.12 Support

### ISSUE THREAD

**Issue by alexjg** [doolse/purescript-reactnative#21]
Hey folks. I spent a little while trying to get this library working with purescript 0.12 over the weekend and ran into some problems. As far as I can tell the main thing that needs doing is removing the dependency on purescript-effect. Is that correct?

**Comment by jvliwanag** [comment]
I've been trying my hand at this, testing out what purescript-reactnative would look like once purescript-contrib/purescript-react#149 gets merged. But I'm currently stuck now since the `Optional` typeclass approach doesn't work right anymore. In particular, I'm running into purescript-contrib/purescript-react#151

**Comment by jvliwanag** [comment]
I have an early build against 0.12 [here](https://github.com/doolse/purescript-reactnative/compare/master...jvliwanag:compiler/0.12). Will submit a pull req once purescript-react gets a tagged version for 0.12

**Comment by doolse** [comment]
Thanks for your work @jvliwanag :+1:
